"""
Schemas Package
"""

from app.schemas.user import (
    UserRole,
    UserBase,
    UserCreate,
    UserLogin,
    UserResponse,
    UserInDB,
    TokenResponse,
    TokenRefresh,
)
from app.schemas.task import (
    TaskCategory,
    TaskDifficulty,
    RiskLevel,
    TaskOption,
    TaskBase,
    TaskCreate,
    TaskUpdate,
    TaskResponse,
    TaskListResponse,
    TaskBrief,
)
from app.schemas.attempt import (
    AttemptStatus,
    CandidateInfo,
    AttemptCreate,
    AttemptResponse,
    AttemptBrief,
    AttemptListResponse,
    AssessmentInfo,
    AttemptStart,
)
from app.schemas.event import (
    EventType,
    EventCreate,
    EventBatchCreate,
    EventResponse,
    EventListResponse,
    WebSocketEvent,
    WebSocketEventLogged,
    WebSocketAttemptStatus,
    WebSocketAssessmentCompleted,
)
from app.schemas.metrics import (
    RiskPreference,
    GlobalMetrics,
    PerTaskMetrics,
    AggregatedPatterns,
    ComputedMetricsResponse,
    MetricsComputeRequest,
)
from app.schemas.resume import (
    CandidateInfoExtracted,
    ResumeParseResponse,
    ATSScoreResponse,
    JobFitRequest,
    JobFitResponse,
    ResumeSuggestionsRequest,
    ResumeSuggestionsResponse,
)
from app.schemas.skill import (
    ThinkingStyleType,
    DecisionSpeed,
    DecisionConsistency,
    RiskOrientationType,
    ReasoningDepthType,
    LogicalStructureType,
    ThinkingStyle,
    DecisionPattern,
    RiskOrientation,
    CommunicationStyle,
    SkillProfileResponse,
    CandidateSkillSummary,
    CandidateListResponse,
    CandidateCompareRequest,
    CandidateCompareResponse,
)
from app.schemas.bulk import (
    BulkJobStatus,
    BulkResultStatus,
    BulkFileResult,
    BulkJobResponse,
    BulkJobStatusResponse,
    BulkEmailRequest,
    BulkEmailResultItem,
    BulkEmailResponse,
    BulkJobListResponse,
)

__all__ = [
    # User
    "UserRole",
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "UserInDB",
    "TokenResponse",
    "TokenRefresh",
    # Task
    "TaskCategory",
    "TaskDifficulty",
    "RiskLevel",
    "TaskOption",
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskListResponse",
    "TaskBrief",
    # Attempt
    "AttemptStatus",
    "CandidateInfo",
    "AttemptCreate",
    "AttemptResponse",
    "AttemptBrief",
    "AttemptListResponse",
    "AssessmentInfo",
    "AttemptStart",
    # Resume
    "CandidateInfoExtracted",
    "ResumeParseResponse",
    "ATSScoreResponse",
    "JobFitRequest",
    "JobFitResponse",
    "ResumeSuggestionsRequest",
    "ResumeSuggestionsResponse",
    # Event
    "EventType",
    "EventCreate",
    "EventBatchCreate",
    "EventResponse",
    "EventListResponse",
    "WebSocketEvent",
    "WebSocketEventLogged",
    "WebSocketAttemptStatus",
    "WebSocketAssessmentCompleted",
    # Metrics
    "RiskPreference",
    "GlobalMetrics",
    "PerTaskMetrics",
    "AggregatedPatterns",
    "ComputedMetricsResponse",
    "MetricsComputeRequest",
    # Skill
    "ThinkingStyleType",
    "DecisionSpeed",
    "DecisionConsistency",
    "RiskOrientationType",
    "ReasoningDepthType",
    "LogicalStructureType",
    "ThinkingStyle",
    "DecisionPattern",
    "RiskOrientation",
    "CommunicationStyle",
    "SkillProfileResponse",
    "CandidateSkillSummary",
    "CandidateListResponse",
    "CandidateCompareRequest",
    "CandidateCompareResponse",
    # Bulk
    "BulkJobStatus",
    "BulkResultStatus",
    "BulkFileResult",
    "BulkJobResponse",
    "BulkJobStatusResponse",
    "BulkEmailRequest",
    "BulkEmailResultItem",
    "BulkEmailResponse",
    "BulkJobListResponse",
]
